package commands

// Dockerfile template for Go projects
const goDockerfileTemplate = `# Multi-stage build for Go
FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY go.mod ./
RUN go mod download

COPY . .
RUN go build -o main ./...

# Final stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/
COPY --from=builder /app/main .
COPY --from=builder /app/.env ./

EXPOSE {{.Port}}
CMD ["./main"]
`

// Dockerfile template for Node.js projects
const nodejsDockerfileTemplate = `FROM node:18-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
EXPOSE {{.Port}}

CMD ["node", "app.js"]
`

// Dockerfile template for Python projects  
const pythonDockerfileTemplate = `FROM python:3.11-alpine

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
EXPOSE {{.Port}}

CMD ["python", "app.py"]
`

// Docker Compose template
const dockerComposeTemplate = `version: '3.8'

services:
  app:
    build: .
    ports:
      - "{{.Port}}:{{.Port}}"
    environment:
      - PORT={{.Port}}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{{.Port}}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Uncomment for database support
  # database:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: {{.ProjectName}}
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   db_data:
`

// DeployGo configuration template
const deploygoConfigTemplate = `version: "1.0"

project:
  name: "{{.ProjectName}}"
  language: "{{.Language}}"

build:
  dockerfile: "./Dockerfile"
  platforms: ["linux/amd64"]
  build_args:
    - "VERSION={{.Version}}"

deploy:
  strategy: "rolling"
  health_check:
    endpoint: "/health"
    timeout: "30s"
    interval: "5s"
  
  rollback:
    enabled: true

environments:
  staging:
    hosts: ["staging.example.com"]
    ssh_user: "deploy"
    
  production:
    hosts: ["prod.example.com"]
    ssh_user: "deploy"
`

// Go application template
const goMainTemplate = `package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
)

func main() {
	http.HandleFunc("/", helloHandler)
	http.HandleFunc("/health", healthHandler)

	port := os.Getenv("PORT")
	if port == "" {
		port = "{{.Port}}"
	}

	log.Printf("Server starting on port %s", port)
	log.Fatal(http.ListenAndServe(":"+port, nil))
}

func helloHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello from %s!", "{{.ProjectName}}")
}

func healthHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	fmt.Fprintf(w, `{"status": "healthy", "service": "%s"}`, "{{.ProjectName}}")
}
`

// Node.js application template
const nodejsAppTemplate = `const http = require('http');

const port = process.env.PORT || {{.Port}};

const server = http.createServer((req, res) => {
  if (req.url === '/health') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ status: 'healthy', service: '{{.ProjectName}}' }));
  } else {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end(` + "`Hello from {{.ProjectName}}!`" + `);
  }
});

server.listen(port, () => {
  console.log(` + "`Server running at http://localhost:${port}/`" + `);
});
`

const nodejsPackageTemplate = `{
  "name": "%s",
  "version": "1.0.0",
  "description": "Generated by DeployGo",
  "main": "app.js",
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {}
}
`

// Python application template
const pythonAppTemplate = `from flask import Flask, jsonify
import os

app = Flask(__name__)

@app.route('/')
def hello():
    return 'Hello from {{.ProjectName}}!'

@app.route('/health')
def health():
    return jsonify({"status": "healthy", "service": "{{.ProjectName}}"})

if __name__ == '__main__':
    port = int(os.environ.get('PORT', {{.Port}}))
    app.run(host='0.0.0.0', port=port)
`

// Docker ignore template
const dockerIgnoreTemplate = `node_modules
__pycache__
*.pyc
.env
.git
.coverage
.nyc_output
.DS_Store
*.log
dist
`